---
title: "Introduction to time series"
output: html_notebook
---

```{r}
library(tsibble)
library(tsibbledata)
library(feasts)
library(fable)
```

```{r}
head(vic_elec)
```
```{r}
index_var(vic_elec)
key_vars(vic_elec)
interval(vic_elec)
```

```{r}
index_var(nyc_bikes)
key_vars(nyc_bikes)

```

```{r}
library(tidyverse)
vic_elec %>% 
  select(Demand, Temperature)

# will always have Time 
```

```{r}
vic_elec %>%
  filter_index("2012-01")
```

```{r}
vic_year <- vic_elec %>% 
  mutate(year = lubridate::year(Date))
```

```{r}
 vic_year %>% 
  group_by(year) %>% 
  summarise(mean_temp = mean(Temperature))
```

```{r}
 vic_year %>% 
  index_by(year) %>% 
  summarise(mean_temp = mean(Temperature))
```

Make plots

```{r}
vic_elec %>% 
  filter(Holiday == FALSE) %>% 
  ggplot() +
  aes(x = Time, y = Temperature) +
  geom_line()
```

```{r}
elec_date <- vic_elec %>% 
  index_by(Date) %>% 
  summarise(mean_temp = mean(Temperature))

elec_date %>% 
  ggplot() +
  aes(x = Date, y = mean_temp) +
  geom_line()
```

### Task 2 mins -

Make the same plot, but for monthly aggregated data

```{r}
vic_elec %>%
  mutate(month = lubridate::month(Date)) %>% 
  index_by(month) %>% 
  summarise(mean_temp = mean(Temperature)) %>% 
  ggplot(aes(x = month, y = mean_temp)) +
  geom_line()
```

```{r}
vic_elec %>%
  mutate(month = lubridate::month(Date, label = TRUE)) %>% 
  index_by(month) %>% 
  summarise(mean_temp = mean(Temperature)) %>% 
  ggplot(aes(x = month, y = mean_temp)) +
  geom_point() +
  geom_line(group = 1)
```

```{r}
library(slider)
```

```{r}
elec_rolling <- vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 1000,
      .after = 1000
    )
  )

elec_rolling
```

```{r}
ggplot(elec_rolling) + 
  geom_line(aes(x = Date, y = Temperature), colour = "grey") + 
  geom_line(aes(x = Date, y = temp_moving_avg), colour = "red")
```

### Task - 5 mins

The slide_dbl() function makes a number of arguments available, so let’s play around with them a little!

    Try setting .before and .after to 100. How does the plot change?
    What happens if you set .complete = TRUE?

```{r}
vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100
    )
  ) %>% 
  ggplot() + 
  geom_line(aes(x = Date, 
                y = Temperature), 
            colour = "grey") + 
  geom_line(aes(x = Date, 
                y = temp_moving_avg), 
            colour = "red")
```

```{r}
vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 1000,
      .after = 1000, 
      .complete = TRUE
    )
  ) %>% 
  ggplot() + 
  geom_line(aes(x = Date, 
                y = Temperature), 
            colour = "grey") + 
  geom_line(aes(x = Date, 
                y = temp_moving_avg), 
            colour = "red")
```

# 4 feasts

```{r}
index(tourism)
key_vars(tourism)
```

```{r}
holidays <- tourism %>%
  filter(Purpose %in% c("Holiday","Business")) %>%
  group_by(State) %>%
  summarise(Trips = sum(Trips))

holidays
```

```{r}
holidays %>% 
  autoplot(Trips) + 
  xlab("Year")
```

```{r}
holidays %>%
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>%
  gg_season(Trips)
```

```{r}
holidays %>%
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>%
  gg_subseries(Trips)
```


