---
title: "Lines"
output: html_notebook
---


```{r}
library(tidyverse)
```


```{r}
# let's write our own line function
line <- function(x, a, b){
  return(a * x + b)
}

# set up x vector and use line() to compute y values
data <- tibble(
  x = seq(-5, 5, 0.1),
  y = line(x, a = 2, b = -1)
)

data %>%
  ggplot(aes(x, y)) +
  geom_line(col = "red") +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)
```

Play around plotting two or three different lines.
    Try a line with a=0
and positive b
    .
    You can use mutate() to overwrite y in data from above
Can we use our line() function to plot a perfectly vertical line?

```{r}
data <- tibble(
  x = seq(-5, 5, 0.1),
  y = line(x, a = 0, b = -1)
)

data %>%
  ggplot(aes(x, y)) +
  geom_line(col = "red") +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)
```

```{r}
data <- tibble(
  x = seq(-5, 5, 0.1),
  y = line(x, a = 2, b = 0)
)

data %>%
  ggplot(aes(x, y)) +
  geom_line(col = "red") +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)
```


```{r}
noisy_line <- read_csv("data/noisy_line.csv")
```

```{r}
noisy_line_plot <- noisy_line %>% 
  ggplot(aes(x,y)) +
  geom_point()

noisy_line_plot
```

```{r}
centroid <- noisy_line %>% 
  summarise(x = mean(x),
            y = mean(y))

centroid
```

```{r}
noisy_line_plot <- noisy_line_plot +
  geom_point(aes(x = centroid$x, y = centroid$y), col = "red", size = 5)
noisy_line_plot
```


```{r}
get_intercept <- function(slope, centroid_x, centroid_y){
  return(centroid_y - slope * centroid_x)
}
```

```{r}
slope = 0.5
noisy_line_plot +
  geom_abline(slope = slope, intercept = get_intercept(slope, centroid$x, centroid$y))
```

Task - 5 mins

Play around with the code chunk above and try to find a slope that fits the data reasonably well.

```{r}
slope = 2.2
noisy_line_plot +
  geom_abline(slope = slope, intercept = get_intercept(slope, centroid$x, centroid$y))
```

```{r}
noisy_line_plot + 
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
mtcars %>% 
  ggplot(aes(wt, mpg)) +
  geom_point() +
  geom_smooth(method = "lm")
```

