---
title: "Bible"
output:
  html_document:
    css: ../../../../styles.css
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center')
```

# Tidyverse

## Summarise

### Summarise in new column

  `summarise(avg_mass_fell = mean(mass_in_g))`

### Floor rounds down

  `floor()`

### Count
  
  `summarise(count = n())`
  
### Sum Count

  `summarise(count = sum(is.na(data1)))`
  
  `summarise(count = sum(total_sighting, na.rm = TRUE))`
  if there's a N/A in the count it will come back N/A, 
  na.rm = removes any N/A
  
## Filter

### For NA

  `filter(is.na(year))`

### For Chr

  `filter(first_name == "Mary")`
  
### For Dbl

  `filter(year > 1999)`
  
## Reanme

  `rename(mass_in_g = mass (g))`


### `nest()` - `unnest()`

Nesting creates a list-column of data frames; unnesting flattens it back out into regular columns.



# Strings


### `str_c()`

Make into one string
  `str_c("this", "is" , "a" , "string")`
Concatenate c() to make separate strings
  `c()`

### Upper case

Turns into Upper case
  `str_to_upper()`

### Lower case

Turns into Lower case
  `str_to_lower()`

### Title
 
Makes the frist letter Upper case
  `str_to_title()`

### Sentence
 

  `str_to_sentence()`
  
## Substring

Can pick out a part of the string, 1 is the start -1 is the end 
  `str_sub(start = 1, end = 5)` 
  `str_sub(-5, -1)`
  
### Split

Will split one string into many part ie on each space
`str_split(" ")`

### Format

formats the result, nsall is how many after the decimal mark, big.mark lets you 
put in , ie 1,000,000, decimal.mark lets you change the . to say
`format(nsmall = 2, big.mark= ",", decimal.mark = ".")`


### upper lower case in regex 

(?i) starts case-insensitive mode

(?-i) turns off case-insensitive mode