---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(GGally)
library(modelr)
library(broom)
library(pROC)
library(caret)
library(readxl)
library(leaps)
```

```{r}
# Reading in the data
telecoms <- read_xlsx("data/telecomms_churn.xlsx") %>%
  clean_names() %>%
  mutate(across(where(is.numeric), ~ coalesce(.x, mean(.x, na.rm = TRUE))))

head(telecoms)

summary(telecoms)

# transform NAs in total charges - see above
```

```{r}
telco_churn <- telecoms %>% 
  select(-customer_id) %>% 
  mutate_if(is.character, as.factor)
```

```{r}
split1 <- telco_churn %>%
  select(gender, senior_citizen, partner, churn)

split2 <- telco_churn %>%
  select(dependents, tenure, phone_service, churn)

split3 <- telco_churn %>%
  select(internet_service, contract, monthly_charges, total_charges, churn)
```

```{r}
split1 %>%
  ggpairs()
```

```{r}
split2 %>%
  ggpairs()
```

```{r}
split3 %>%
  ggpairs()
```


```{r}
regsubsets_backward <- regsubsets(churn ~ ., 
                                  data = telco_churn, 
                                  nvmax = 12, method = "backward")

plot(regsubsets_backward, scale = "bic")
```

