---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
```


```{r}

late_deliveries <- read_csv("lab_data/late_deliveries.csv")
recovery_times <-  read_csv("lab_data/recovery_times.csv")
fitness_levels <-  read_csv("lab_data/fitness_levels.csv")

```
# Task 1: do the lab

## Four categories

### Comparison

```{r}
late_deliveries_label <- late_deliveries %>%
  mutate(label_text = ifelse(data == c("2015-12-01",
                                       "2016-12-01",
                                       "2017-12-01"), 
                             "Spikes in the winter months", NA))


late_deliveries_label %>% 
  ggplot(aes(date, late_deliveries), colour = date == c("2015-12-01", "2016-12-01", "2017-12-01")) +
  geom_point() +
  geom_line() +
  scale_colour_manual(values = c("grey60","darkgreen"), guide = "none") +
  ylim(45, 200) +
  ylab("Number of late deliveries")
```



```{r}
late_deliveries %>% 
  ggplot(aes(date, late_deliveries)) +
  geom_point() +
  geom_line() +
  ylim(45, 200) +
  ylab("Number of late deliveries")
```


```{r}
recovery_times %>%
  mutate(prognosis = factor(prognosis, levels = c("Excellent", "Good", "Average", "Poor"))) %>%
  ggplot(aes(treatment_group, recovery, fill = prognosis)) +
  geom_col(position = "dodge") +
  coord_flip() +
  scale_fill_brewer(palette = "Blues")
```

```{r}
fitness_levels %>% 
  group_by(child, age, group) %>%
  summarise(fitness_lvl = sum(fitness_score)) %>%
  ggplot(aes(age, fitness_lvl, fill = child)) +
  geom_col(position = "dodge") +
  facet_wrap(~ child) +
  ylab("Fitness level") +
  xlab("Age")

fitness_levels %>% 
  group_by(child, age, group) %>% 
  summarise(fitness = sum(fitness_score)) %>%
  ggplot(aes(age, fitness, colour = child)) +
  geom_line() +
  facet_wrap(~group) +
  ylab("Fitness level") +
  xlab("Age")
```

### Connection
```{r}

blood_pressure <- read_csv("lab_data/blood_pressure.csv")
car_use <- read_csv("lab_data/car_use.csv")

```

```{r}
blood_pressure %>%
  ggplot(aes(
    daily_saturated_fat_intake_mg, systolic_blood_pressure_mm_hg,
    colour = systolic_blood_pressure_mm_hg)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + # liner modeld
  labs(x = "\n Daily fat intake \n (mg)",
       y = "\n Blood pressure \n (mmHg) \n") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
car_use %>% 
  mutate(car_users = car_use_percent * population) %>% 
  ggplot(aes(car_users, air_so2_concentration_ppm, colour = population)) +
  geom_point() +
  geom_smooth(se = F) +
  labs(x = "\n Number of car users per city \n",
       y = "\n SO2 concentrarion \n (ppm)\n") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
car_use %>% 
  mutate(car_users = car_use_percent * population) %>% 
  ggplot(aes(car_users, air_so2_concentration_ppm, 
             colour = population, size = population)) +
  geom_point() +
  scale_colour_gradient(low = "gray0", high = "gray100") +
  geom_smooth(se = F) +
  labs(x = "\n Number of car users per city \n",
       y = "\n SO2 concentrarion \n (ppm)\n") +
  theme_minimal()
```


### Distribution
```{r}

d20_outcomes <- read_csv("lab_data/d20_outcomes.csv")
d20x5_outcomes <- read_csv("lab_data/d20x5_outcomes.csv")

```

```{r}
d20_outcomes %>% 
  ggplot(aes(outcome)) + 
  geom_bar(fill = "Blue") +
  scale_x_continuous(breaks = seq(0, 20, 2)) +
  labs(title = "\n d20 test \n",
       x = "\n Outcome of a d20 \n",
       y = "\n Number of times rolled \n") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
d20x5_outcomes %>% 
  group_by(outcome) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(outcome, count)) + 
  # geom_density(alpha = 0.9, colour = "darkgreen") +
  geom_col(alpha = 0.2)


d20x5_outcomes %>% 
  ggplot(aes(outcome)) + 
  geom_density(alpha = 0.9, colour = "green")
  # geom_bar()
```

### Class work out
```{r}
ggplot(d20x5_outcomes) +
  aes(x = outcome) +
  geom_histogram(aes(y = ..density..), bins = 20, col = "white") +
  geom_density()
```


### Composition

```{r}

pension_surplus <- read_csv("lab_data/pension_surplus.csv")
pension_liabilities <- read_csv("lab_data/pension_liabilities.csv")

```


```{r}
pension_surplus %>%
  ggplot(aes(sign, fill = item)) +
  geom_bar()
```



```{r}
pension_liabilities %>% 
  mutate(liability_type = factor(
    liability_type, levels = c("actives", 
                                "deferred", 
                                "pensioners", 
                                "widowed_people"))) %>%
  ggplot(aes(year, liability_millions, fill = liability_type)) +
  geom_col(colour = "black") +
  scale_fill_brewer(palette = "Reds") +
  labs(title = "\n Pension Liabilities\n",
       y = "\n Liability in Millions\n",
       x = "\n Years\n",
       fill = "Liability Type") +
  theme(plot.title = element_text(hjust = 0.5))
  
```

# Task 2 (mandatory) : make the worst graph you can
```{r}
fitness_levels %>%
  group_by(child, age, group) %>%
  summarise(fitness = sum(fitness_score)) %>%
  # mutate(rand = sample(1:200)) %>%
  ggplot(aes(age, fitness, colour = "black")) +
  geom_path(aes(colour = "magenta")) +
  geom_col(aes(colour = "darkbrown")) +
  geom_point(aes(colour = "blue")) +
  geom_point(aes(colour = "turquoise")) +
  facet_grid(child~age) +
  theme_classic(26) +
  labs(title =  "child by group by fitness by age",
       subtitle = ("\n\n\n\n\n\n\n"))
```

```{r}
fitness_levels %>%
  group_by(child, age, group) %>% 
  summarise(fitness = sum(fitness_score)) %>%
  # mutate(rand = sample(1, 200)) %>%
  ggplot(aes(age, fitness, colour = "black", size = age)) +
  geom_path(aes(colour = "magenta", size = group)) +
  geom_point(aes(colour = "blue")) +
  geom_point(aes(colour = "turquoise")) +
  theme_classic(26) +
  theme(axis.text.x = element_text(angle = 190, hjust = 0.1, colour = "lightgreen"),
        axis.text.y = element_text(angle = 250, hjust = 1),
        panel.background = element_rect(fill = "tomato"),
        plot.background = element_rect(fill = "#FF00FF"),
        axis.text = element_text(size = rel(0.8), angle = 45),
        axis.ticks = element_line(colour = "#9867FA"),
        legend.key = element_rect(colour = "#7FFF00"),
        panel.border = element_rect(fill = NA, colour = "#800000"),
        panel.grid.major = element_line(colour = "#0000FF", size = 3),
        panel.grid.minor = element_line(colour = "grey98", size = 1),
        axis.title = element_text(size = 30, angle = 30, hjust = 0),
        strip.background = element_rect(fill = "blue80", colour = "grey50")
        ) +
  labs(title =  toupper("childbygroupby fitness by age cHiLdByGRoUpByFitNeSsByAgE"), 
       subtitle = ("cHiLdByGRoUpByFitNeSsByAgE\n \n І 	К 	Л 	М 	Н 	Ѯ 	Ѻ 	П 	Ч"),
       ) +
  scale_fill_brewer(palette = "Set2") +
  coord_flip() +
  xlab("age by child by fitness by group by level by ")
```


