---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

customers table 
```{r}
# makes a tibble(table)
customers <- tibble(
  customer_ID = c(001, 002, 004, 005, 008, 010), 
  name = c("John Smith", "Jane Adams", "Robert Landry", "Jane Tow", "Raul Tann", "Hilary Joyal"),
  email_address = c("johnsmith@gmail.com", "janea@gmail.com", "rlabdry@hotmail.com", "janet89@aol.com", "paul.tann1@gmail.com", NA),
  shipping_address = c("32 Station Road, Edinburgh", "42 Park Drive, Edinburgh", NA, "10 Gardiner Rd, Edinburgh", "12 Main St, Edinburgh", " 234 Queensferry Rd, Edinburgh,")
)

customers
# customer_ID primary key
```

orders table
```{r}
orders <- tibble(
  customer_ID = c(001, 002, 005, 010, 012, 001), 
  order_number = c("KU65781", "SU98201", "JS76821", "YR28212", "JS91221","YR21873"),
  order_total = c("£32.50", "£56.00", "£100.02", "£20.25", "£39.50", "£45.00"),
  product_code = c("XZY780", "XYZ123", "XYZ256", "XYZ262", "XYZ345", "XYZ127")
)
orders

# order_number primary key
# customer_ID foranin key
```

inner-join
```{r}
inner_join(customers, orders, by = "customer_ID") # don't need the by =, reads better 
                                                  # taking out by = "customer_ID" gives the same but also ells you that it's joined by "customer_ID"
```

Left join
```{r}
left_join(customers, orders, by = "customer_ID")
```

Right join
```{r}
right_join(customers, orders, by = "customer_ID")
```

Full join
```{r}
full_join(customers, orders)
```

Differnt name primary key join
```{r}
customers_adj <- customers %>% 
  rename(this_is_an_id = customer_ID)

inner_join(customers_adj, orders, by = 
             c("this_is_an_id" = "customer_ID"))
```

joining on two points
```{r}
# create a new column in both tables
customers2 <- customers %>% 
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "card"))

orders2 <- orders %>%
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "cash"))

# join by one columns
inner_join(customers2, orders2, by = "customer_ID")

# join by two columns
inner_join(customers2, orders2, by = c("customer_ID", "payment_type"))
```

semi_join 
```{r}
semi_join(customers, orders) # tell me in R console Joining, by = "customer_ID"
# shows customers that made at least one order
```

anti_join
```{r}
anti_join(customers, orders)
# shows customers that have not made at least one order
```

Binding verbs
bind_cols
```{r}
statuses <- tibble(
  status = c("active", "active", "inactive", "inactive", "active", "inactive")
) 

bind_cols(customers, statuses)
```

bind_rows
```{r}
past_customers <- tibble(
  customer_ID = c(020, 021), 
  name = c("Dave Brown", "Jess Bishop"),
  email_address = c("dbrown@hotmail.com", "jessb@gmail.com"),
  shipping_address = c("57 Park View, Leith", "12 Reid Way, Broxburn")
)

bind_rows(customers, past_customers)
```

